import { useEffect, useState } from 'react';
import { Link, Navigate, Outlet, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { adminDashboard, currentUser, login, publicContent, register, type AdminDashboard, type SessionUser } from './api';
import { ContentManagement } from './ContentManagement';
import { AcademicSetupPage } from './AcademicSetupPage';
import { StudentResultsPage } from './StudentResultsPage';
import { ExploreDirectory, ExplorePage } from './ExploreSapienza';
import './academic.css';

type Notice = { title: string; body: string; category: string };

function roleNames(user: SessionUser | null) { return user?.roles?.map((role) => role.name) ?? []; }
function homeFor(user: SessionUser) {
  const roles = roleNames(user);
  return roles.includes('super_admin') || roles.includes('admin') ? '/admin' : roles.includes('teacher') ? '/staff' : '/student';
}

function PublicLayout({ user, onLogout }: { user: SessionUser | null; onLogout: () => void }) {
  return <main className="page-shell"><nav><Link className="brand" to="/"><strong>SAPIENZA</strong><span>Catholic School</span></Link><div className="nav-actions">{user ? <><Link to={homeFor(user)}>Open portal</Link><button onClick={onLogout}>Sign out</button></> : <><Link to="/register">Create account</Link><Link to="/login">Sign in</Link></>}</div></nav><Outlet /></main>;
}

function Landing({ user }: { user: SessionUser | null }) {
  const [notices, setNotices] = useState<Notice[]>([]);
  const [heroImage, setHeroImage] = useState<string>();
  useEffect(() => { publicContent().then(([noticeData, mediaData]) => { setNotices(noticeData.notices); setHeroImage(mediaData.media.find((asset) => asset.key === 'homepage.hero')?.url); }).catch(() => undefined); }, []);
  return <><section className="hero" style={heroImage ? { backgroundImage: `linear-gradient(90deg, rgba(244,241,233,.96), rgba(244,241,233,.2)), url(${heroImage})` } : undefined}><p className="eyebrow">Forming minds. Shaping character.</p><h1>Learn with purpose.<br /><em>Live with faith.</em></h1><p className="intro">A connected school community for students, families, teachers, and alumni.</p><div className="actions"><Link className="primary" to="/explore">Explore Sapienza</Link><Link className="text-button" to="/admissions">Admissions <span>↗</span></Link></div></section><section className="portal-strip portals"><div><small>PORTALS</small><h2>Choose the space that fits your role.</h2></div><div className="portal-links"><Link to={user ? '/student' : '/login'}>Student Portal <span>→</span></Link><Link to={user && roleNames(user).some((role) => ['teacher', 'admin', 'super_admin'].includes(role)) ? '/staff' : '/login'}>Staff Portal <span>→</span></Link><Link to={user && roleNames(user).some((role) => ['admin', 'super_admin'].includes(role)) ? '/admin' : '/login'}>Admin Portal <span>→</span></Link></div></section><section id="notices" className="portal-strip"><div><small>NOTICE BOARD</small><h2>What is happening at Sapienza.</h2></div><div className="notice-list">{notices.length ? notices.slice(0, 3).map((notice) => <article key={notice.title}><small>{notice.category}</small><h3>{notice.title}</h3><p>{notice.body}</p></article>) : <p className="muted">New school announcements will appear here.</p>}</div></section></>;
}

function Admissions() { return <section className="admissions"><small>ADMISSIONS</small><h2>Begin your Sapienza journey.</h2><p>Our admissions team helps families understand programs, application steps, and the life of the school.</p><Link className="text-button" to="/register">Create a family account <span>↗</span></Link></section>; }

function AuthPage({ mode, onAuthenticated }: { mode: 'login' | 'register'; onAuthenticated: (user: SessionUser) => void }) {
  const navigate = useNavigate(); const [firstName, setFirstName] = useState(''); const [lastName, setLastName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const result = mode === 'login' ? await login(email, password) : await register(firstName, lastName, email, password); localStorage.setItem('sapienza.token', result.token); const session = await currentUser(); onAuthenticated(session.user); navigate(homeFor(session.user)); } catch (authError) { setError(authError instanceof Error ? authError.message : 'Unable to continue'); } finally { setLoading(false); } }
  return <div className="auth-page"><form className="login-panel" onSubmit={submit}><small>{mode === 'login' ? 'SCHOOL PORTAL' : 'JOIN SAPIENZA'}</small><h2>{mode === 'login' ? 'Sign in to continue.' : 'Create your account.'}</h2>{mode === 'register' && <div className="name-fields"><label>First name<input value={firstName} onChange={(event) => setFirstName(event.target.value)} required /></label><label>Last name<input value={lastName} onChange={(event) => setLastName(event.target.value)} required /></label></div>}<label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Password<input type="password" minLength={mode === 'register' ? 8 : undefined} value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={loading}>{loading ? 'Please wait...' : mode === 'login' ? 'Sign in' : 'Create account'}</button><Link className="text-button" to={mode === 'login' ? '/register' : '/login'}>{mode === 'login' ? 'Need an account? Create one' : 'Already have an account? Sign in'}</Link></form></div>;
}

function ProtectedRoute({ user, roles }: { user: SessionUser | null; roles?: string[] }) { if (!user) return <Navigate to="/login" replace />; if (roles && !roles.some((role) => roleNames(user).includes(role))) return <Navigate to={homeFor(user)} replace />; return <AuthenticatedLayout user={user} />; }
function PermissionRoute({ user, permission }: { user: SessionUser | null; permission: string }) { if (!user) return <Navigate to="/login" replace />; if (!user.roles?.some((role) => role.permissions.includes(permission))) return <Navigate to={homeFor(user)} replace />; return <AuthenticatedLayout user={user} />; }
function AuthenticatedLayout({ user }: { user: SessionUser }) { const navigate = useNavigate(); const location = useLocation(); const [menuOpen, setMenuOpen] = useState(true); const roles = roleNames(user); const admin = roles.includes('admin') || roles.includes('super_admin'); const staff = roles.some((role) => ['teacher', 'admin', 'super_admin'].includes(role)) || (user.roles?.some((role) => role.permissions.includes('academics:manage')) && !roles.includes('student')); const permissions = user.roles?.flatMap((role) => role.permissions) ?? [];
  const canManageSchoolContent = permissions.includes('content:manage') || permissions.includes('media:manage');
  const canManageAcademics = permissions.includes('academics:manage');
  const links = admin ? [['Dashboard', '/admin'], ['Users & roles', '/admin/users'], ['Academics', '/admin/academics'], ['Finance', '/admin/finance'], ['Reports', '/admin/reports']] : staff ? [['Dashboard', '/staff'], ['Attendance', '/staff/attendance'], ['Assignments', '/staff/assignments'], ['Grades', '/staff/grades'], ['CBT', '/staff/cbt']] : [['Dashboard', '/student'], ['Academic records', '/student/records'], ['Assignments', '/student/assignments'], ['CBT', '/student/cbt'], ['Fees', '/student/fees']];
  const navigationLinks = [...(canManageAcademics && !admin ? [...links, ['Academic setup', '/academic-setup']] : links), ...(canManageSchoolContent ? [['Content & media', '/content-management']] : [])];
  return <main className={`portal-shell${menuOpen ? '' : ' nav-collapsed'}`}><aside><div className="sidebar-top"><Link className="brand" to="/"><strong>SAPIENZA</strong><span>Portal</span></Link><button className="menu-toggle" type="button" aria-label={menuOpen ? 'Collapse navigation' : 'Expand navigation'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span aria-hidden="true">☰</span></button></div><small className="portal-role">{admin ? 'ADMINISTRATION' : staff ? 'STAFF PORTAL' : 'STUDENT PORTAL'}</small><div className="side-links">{navigationLinks.map(([label, path]) => <Link aria-label={label} title={label} className={location.pathname === path ? 'active' : ''} key={path} to={path}><span className="nav-label">{label}</span><span aria-hidden="true">→</span></Link>)}</div><button className="signout" onClick={() => { localStorage.removeItem('sapienza.token'); navigate('/'); }}>Sign out</button></aside><section className="portal-content"><header><small>{user.firstName} {user.lastName}</small><h1>{navigationLinks.find(([, path]) => path === location.pathname)?.[0] ?? 'Dashboard'}</h1></header><Outlet /></section></main>; }

function AdminOverview() {
  const [data, setData] = useState<AdminDashboard | null>(null);
  const [error, setError] = useState('');
  const [retryKey, setRetryKey] = useState(0);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    let active = true;
    setLoading(true);
    setError('');
    adminDashboard().then((result) => { if (active) setData(result); }).catch((requestError) => { if (active) setError(requestError instanceof Error ? requestError.message : 'Unable to load dashboard data'); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [retryKey]);
  const number = (value: number) => new Intl.NumberFormat().format(value);
  const money = (value: number) => new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(value);
  if (loading) return <section className="admin-overview" aria-live="polite"><p className="muted">Loading school overview...</p></section>;
  if (error) return <section className="admin-overview overview-error" role="alert"><p>{error}</p><button type="button" onClick={() => setRetryKey((key) => key + 1)}>Try again</button></section>;
  if (!data) return null;
  const attendanceTotal = data.attendance.reduce((total, item) => total + item.count, 0);
  return <section className="admin-overview" aria-label="School overview">
    <div className="overview-metrics">
      <article><small>ACTIVE STUDENTS</small><strong>{number(data.students)}</strong></article>
      <article><small>ATTENDANCE RECORDS</small><strong>{number(attendanceTotal)}</strong><span>Across all recorded statuses</span></article>
      <article><small>COLLECTED</small><strong>{money(data.finance.collected)}</strong><span>Of {money(data.finance.billed)} billed</span></article>
      <article><small>OUTSTANDING</small><strong>{money(data.finance.outstanding)}</strong><span>{number(data.invoices.reduce((total, invoice) => total + invoice.count, 0))} invoices</span></article>
      <article><small>CBT ATTEMPTS</small><strong>{number(data.cbt.attempts)}</strong><span>{data.cbt.averagePercentage.toFixed(1)}% average score</span></article>
    </div>
    <div className="overview-attendance"><div><small>ATTENDANCE BREAKDOWN</small><h3>Recorded attendance</h3></div>{data.attendance.length ? <dl>{data.attendance.map((item) => <div key={item._id}><dt>{item._id}</dt><dd>{number(item.count)}</dd></div>)}</dl> : <p className="muted">No attendance records yet.</p>}</div>
  </section>;
}

function DashboardPage({ kind }: { kind: 'student' | 'staff' | 'admin' }) { const copy = { student: ['Your school day, in one place.', 'Review your records, assignments, tests, and fees.'], staff: ['Keep the school moving forward.', 'Manage attendance, learning, grades, and assessments.'], admin: ['The school at a glance.', 'Manage people, operations, finance, content, and reports.'] }[kind]; const modules = { student: [['Academic records', '/student/records', 'REVIEW', 'See your grades and attendance.'], ['Assignments', '/student/assignments', 'LEARNING', 'View work and submission status.'], ['CBT', '/student/cbt', 'ASSESSMENTS', 'Open tests and assessment history.'], ['Fees', '/student/fees', 'ACCOUNT', 'Review school fees and payments.']], staff: [['Attendance', '/staff/attendance', 'CLASSROOM', 'Open class registers and attendance.'], ['Assignments', '/staff/assignments', 'LEARNING', 'Manage learning tasks and submissions.'], ['Grades', '/staff/grades', 'RECORDS', 'Enter and review student grades.'], ['CBT', '/staff/cbt', 'ASSESSMENTS', 'Manage computer-based tests.']], admin: [['Users & roles', '/admin/users', 'PEOPLE', 'Manage accounts and access.'], ['Academics', '/admin/academics', 'LEARNING', 'Open classes, subjects, and school years.'], ['Finance', '/admin/finance', 'OPERATIONS', 'Review fees and payment records.'], ['Reports', '/admin/reports', 'INSIGHTS', 'Open school reporting tools.']] }[kind]; return <div className="dashboard-grid"><article className="dashboard-lead"><small>OVERVIEW</small><h2>{copy[0]}</h2><p>{copy[1]}</p></article>{kind === 'admin' && <div className="dashboard-wide"><AdminOverview /></div>}{modules.map(([label, path, category, description]) => <Link className="dashboard-tile" key={path} to={path}><small>{category}</small><h3>{label}</h3><p>{description}</p><span className="tile-arrow" aria-hidden="true">→</span></Link>)}</div>; }
function PlaceholderPage() { const location = useLocation(); const segments = location.pathname.split('/').filter(Boolean); const title = segments[segments.length - 1]?.replace(/-/g, ' ') ?? 'Workspace'; return <div className="empty-state"><small>WORKSPACE</small><h2>{title.replace(/\b\w/g, (letter) => letter.toUpperCase())}</h2><p className="muted">This module is connected to your role. Live records and actions will appear here as the module is configured.</p></div>; }

export function App() { const [user, setUser] = useState<SessionUser | null>(null); useEffect(() => { if (localStorage.getItem('sapienza.token')) currentUser().then(({ user: nextUser }) => setUser(nextUser)).catch(() => { localStorage.removeItem('sapienza.token'); setUser(null); }); }, []); return <Routes><Route element={<PublicLayout user={user} onLogout={() => { localStorage.removeItem('sapienza.token'); setUser(null); }} />}><Route path="/" element={<Landing user={user} />} /><Route path="/explore" element={<ExploreDirectory />} /><Route path="/explore/:slug" element={<ExplorePage />} /><Route path="/admissions" element={<Admissions />} /><Route path="/login" element={<AuthPage mode="login" onAuthenticated={setUser} />} /><Route path="/register" element={<AuthPage mode="register" onAuthenticated={setUser} />} /></Route><Route element={<ProtectedRoute user={user} />}><Route path="/content-management" element={<ContentManagement user={user!} />} /></Route><Route element={<PermissionRoute user={user} permission="academics:manage" />}><Route path="/academic-setup" element={<AcademicSetupPage />} /></Route><Route element={<ProtectedRoute user={user} roles={['student']} />}><Route path="/student" element={<DashboardPage kind="student" />} /><Route path="/student/records" element={<StudentResultsPage />} /><Route path="/student/*" element={<PlaceholderPage />} /></Route><Route element={<ProtectedRoute user={user} roles={['teacher', 'admin', 'super_admin']} />}><Route path="/staff" element={<DashboardPage kind="staff" />} /><Route path="/staff/*" element={<PlaceholderPage />} /></Route><Route element={<ProtectedRoute user={user} roles={['admin', 'super_admin']} />}><Route path="/admin" element={<DashboardPage kind="admin" />} /><Route path="/admin/academics" element={<AcademicSetupPage />} /><Route path="/admin/*" element={<PlaceholderPage />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
